Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/alex/.pyenv/versions/3.8.5/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axs = plt.subplots(1, 3, figsize=(18, 6))

heatmap(Bhat,
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$\hat B_{SBM}$",
        ax=axs[0])

heatmap(np.array(B),
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$B_{SBM}$",
        ax=axs[1])

heatmap(np.abs(Bhat - np.array(B)),
        vmin=0,
        vmax=1,
        font_scale=1.5,
        title="$|\hat B_{SBM} - B_{SBM}|$",
        ax=axs[2])

fig;
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m<ipython-input-34-a112421e2ac5>[0m in [0;36m<module>[1;34m[0m
[0;32m     15[0m         ax=axs[1])
[0;32m     16[0m [1;33m[0m[0m
[1;32m---> 17[1;33m heatmap(np.abs(Bhat - np.array(B)),
[0m[0;32m     18[0m         [0mvmin[0m[1;33m=[0m[1;36m0[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m     19[0m         [0mvmax[0m[1;33m=[0m[1;36m1[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: operands could not be broadcast together with shapes (2,2) (3,3) 
ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

